// Generated by CoffeeScript 1.4.0
var async;

async = require("async");

async["if"] = function(condition, errMsg, callback) {
  if (condition) {
    return callback(null);
  } else {
    return callback(new Error(errMsg));
  }
};

async.endif = function(messages, err) {
  var message, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = messages.length; _i < _len; _i++) {
    message = messages[_i];
    if (message.msg === err.message) {
      message.action();
      break;
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};
